name: Frontend CI

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Node ${{ matrix.node-version }} Test
    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Verify Node and npm versions
        run: |
          node -v
          npm -v

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Check code formatting with Prettier
        working-directory: ./frontend
        run: |
          if npm list prettier > /dev/null 2>&1; then
            npx prettier --check "src/**/*.{ts,html,scss,css}" || echo "Prettier check failed - formatting issues found"
          else
            echo "Prettier not available, skipping format check"
          fi

      - name: Run tests
        working-directory: ./frontend
        run: npm run test -- --watch=false --browsers=ChromeHeadless --code-coverage

      - name: Build application
        working-directory: ./frontend
        run: npm run build

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-node-${{ matrix.node-version }}
          path: frontend/coverage/
          retention-days: 7

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: build-artifacts-node-${{ matrix.node-version }}
          path: frontend/dist/
          retention-days: 7