name: Full CI (Backend + Frontend)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  backend:
    runs-on: ubuntu-latest
    name: Backend - Java 21
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run backend tests
        run: mvn clean test

      - name: Package backend
        run: mvn package -DskipTests

      - name: Upload backend test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: backend-test-results
          path: target/surefire-reports/
          retention-days: 7

  frontend:
    runs-on: ubuntu-latest
    name: Frontend - Node 20
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Run frontend tests
        working-directory: ./frontend
        run: npm run test -- --watch=false --browsers=ChromeHeadless --code-coverage

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      - name: Upload frontend test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: frontend-test-results
          path: frontend/coverage/
          retention-days: 7

      - name: Upload frontend build artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: frontend-build-artifacts
          path: frontend/dist/
          retention-days: 7

  integration:
    runs-on: ubuntu-latest
    name: Integration Tests
    needs: [backend, frontend]
    if: success()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build all components
        run: |
          mvn package -DskipTests
          cd frontend && npm run build

      - name: Start backend for integration tests
        run: |
          mvn quarkus:dev &
          sleep 30

      - name: Run integration smoke tests
        run: |
          curl -f http://localhost:8080/hello || (echo "Backend health check failed" && exit 1)
          curl -f http://localhost:8080/q/health || (echo "Backend health endpoint failed" && exit 1)

      - name: Stop backend
        run: pkill -f quarkus:dev || true